TimesheetSystem/TimesheetSystem/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimesheetSystem.DAL;
using TimesheetSystem.DAL.Models;

namespace TimesheetSystem.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private UnitOfWork repositories = new UnitOfWork();

        // GET: Projects
        public ActionResult Index()
        {
            return View(repositories.ProjectRepository.GetAllProjects());
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectName,ProjectType,ProjectDateStarted,EstimatedProjectDateEnd")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.EstimatedDuration = project.EstimatedProjectDateEnd.Subtract(project.ProjectDateStarted).Days + 1;
                project.TotalDuration = DateTime.Now.Subtract(project.ProjectDateStarted).Days + 1;
                project.ProjectStatus = "Ongoing";

                repositories.ProjectRepository.CreateProject(project);
                repositories.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = repositories.ProjectRepository.GetProject(id.Value);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectId,ProjectName,ProjectType,ProjectDateStarted,EstimatedProjectDateEnd,EstimatedDuration,TotalDuration,ProjectStatus")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.EstimatedDuration = project.EstimatedProjectDateEnd.Subtract(project.ProjectDateStarted).Days + 1;
                project.TotalDuration = DateTime.Now.Subtract(project.ProjectDateStarted).Days + 1;
                repositories.ProjectRepository.UpdateProject(project);
                repositories.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = repositories.ProjectRepository.GetProject(id.Value);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repositories.ProjectRepository.RemoveProject(id);
            repositories.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult UpdateStatus(int id)
        {
            Project project = repositories.ProjectRepository.GetProject(id);
            if (project.ProjectStatus == "Ongoing")
            {
                project.ProjectStatus = "Finished";
            }
            else
            {
                project.ProjectStatus = "Ongoing";
            }

            repositories.SaveChanges();
            var result = new { identifier = project.ProjectId, newStatus = project.ProjectStatus };

            return Json(result);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repositories.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TimesheetSystem/TimesheetSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Personal Timesheet System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container">
        <div class="navbar navbar-inverse navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Personal Timesheet", "Index", "Projects", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if(Request.IsAuthenticated){
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Projects", "Index", "Projects")</li>
                        <li>@Html.ActionLink("Tasks", "AllTasks", "Tasks")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>

        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Personal Timesheet</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>