TimesheetSystem/TimesheetSystem/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimesheetSystem.DAL;
using TimesheetSystem.DAL.Models;
using TimesheetSystem.ViewModels;

namespace TimesheetSystem.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private UnitOfWork repositories = new UnitOfWork();

        
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectTasksViewModel projectTasks = new ProjectTasksViewModel();
            projectTasks.Project = repositories.ProjectRepository.GetProject(id.Value);
            projectTasks.Tasks = repositories.TasksRepository.GetAllTasksUnderProject(id.Value);

            return View(projectTasks);
        }

        public ActionResult AllTasks()
        {
            return View(repositories.TasksRepository.GetAllTasks());
        }

        // GET: Tasks/Create
        public ActionResult Create(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(new Tasks() { ProjectId = id.Value });
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TasksName,TaskType,TaskStartDate,EstimatedTaskDateEnd,TasksStatus,ProjectId")] Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                tasks.TasksStatus = "Ongoing";
                tasks.TaskDuration = tasks.EstimatedTaskDateEnd.Subtract(tasks.TaskStartDate).Days + 1;
                repositories.TasksRepository.CreateTask(tasks);
                repositories.SaveChanges();
                return RedirectToAction("Index", new { id = tasks.ProjectId } );
            }
        
            return View(tasks);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tasks tasks = repositories.TasksRepository.GetTask(id.Value);
            if (tasks == null)
            {
                return HttpNotFound();
            }

            return View(tasks);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TasksId,TasksName,TaskType,TaskStartDate,EstimatedTaskDateEnd,TaskDuration,TasksStatus,ProjectId")] Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                tasks.TaskDuration = tasks.EstimatedTaskDateEnd.Subtract(tasks.TaskStartDate).Days + 1;
                repositories.TasksRepository.UpdateTask(tasks);
                repositories.SaveChanges();
                return RedirectToAction("Index", new { id = tasks.ProjectId });
            }
            ViewBag.ProjectId = new SelectList(repositories.ProjectRepository.GetAllProjects() , "ProjectId", "ProjectName", tasks.ProjectId);

            return View(tasks);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tasks tasks = repositories.TasksRepository.GetTask(id.Value);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            return View(tasks);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int projectId = repositories.TasksRepository.GetTask(id).ProjectId;

            repositories.TasksRepository.RemoveTask(id);
            repositories.SaveChanges();

            return RedirectToAction("Index", new { id = projectId });
        }

        [HttpPost]
        public JsonResult UpdateStatus(int id)
        {
            Tasks task = repositories.TasksRepository.GetTask(id);
            if (task.TasksStatus == "Ongoing")
            {
                task.TasksStatus = "Finished";
            }
            else
            {
                task.TasksStatus = "Ongoing";
            }

            repositories.SaveChanges();
            var result = new { identifier = task.TasksId, newStatus = task.TasksStatus };
            
            return Json(result);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repositories.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TimesheetSystem/TimesheetSystem/Views/Tasks/AllTasks.cshtml
@model IEnumerable<TimesheetSystem.DAL.Models.Tasks>
@{
    ViewBag.Title = "All Tasks";
}

<h2>All Tasks</h2>

<div class="table-responsive">

    <table class="table table-striped">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Project.ProjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TasksName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TasksStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskType)
            </th>
            <th>
                Options
            </th>
        </tr>


        @foreach (var task in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(task.Project.ProjectName, "Index", "Tasks", new { id = task.ProjectId }, null)
                </td>
                <td>

                    @Html.ActionLink(task.TasksName, "Index", "TimeLogs", new { id = task.TasksId }, null)
                </td>
                <td>
                    @Html.DisplayFor(t => task.TasksStatus)
                </td>
                <td>
                    @Html.DisplayFor(t => task.TaskType)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = task.TasksId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = task.TasksId })
                </td>
            </tr>
        }
    </table>
</div>

TimesheetSystem/TimesheetSystem/Views/Tasks/Create.cshtml
@model TimesheetSystem.DAL.Models.Tasks

@{
    ViewBag.Title = "Create Task";
}

<h2>Create Task</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TasksName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TasksName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TasksName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstimatedTaskDateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstimatedTaskDateEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstimatedTaskDateEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ProjectId )

        @*<div class="form-group">
            @Html.LabelFor(model => model.ProjectId, "ProjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", new { id = Model.ProjectId }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TimesheetSystem/TimesheetSystem/Views/Tasks/Delete.cshtml
@model TimesheetSystem.DAL.Models.Tasks

@{
    ViewBag.Title = "Delete Task";
}

<h2>Delete Task</h2>

<h3>Are you sure you want to delete this task?</h3>
<div>
    <hr />

    <div class="row">
        <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.ProjectName):</div>
        <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.ProjectName)</div>
        <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.TaskStartDate):</div>
        <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.TaskStartDate)</div>
    </div>

    <div class="row">
        <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.TasksName):</div>
        <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.TasksName)</div>
        <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.EstimatedTaskDateEnd):</div>
        <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.EstimatedTaskDateEnd)</div>
    </div>

    <div class="row">
        <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.TaskType):</div>
        <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.TaskType)</div>
        <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.TasksStatus):</div>
        <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.TasksStatus)</div>
    </div>

    <div class="row">
        <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.TaskDuration):</div>
        <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.TaskDuration)</div>
    </div>


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color top-pad">
        <input type="submit" value="Delete" class="btn btn-primary" />
        @Html.ActionLink("Back to List", "Index", new { id = Model.ProjectId }, new { @class = "btn btn-primary" })
    </div>
    }
</div>

TimesheetSystem/TimesheetSystem/Views/Tasks/Edit.cshtml
@model TimesheetSystem.DAL.Models.Tasks

@{
    ViewBag.Title = "Edit Task";
    List<SelectListItem> items = new List<SelectListItem>();

    items.Add(new SelectListItem { Text = "Ongoing", Value = "Ongoing" });
    items.Add(new SelectListItem { Text = "Finished", Value = "Finished" });
}

<h2>Edit Task</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TasksId)
        @Html.HiddenFor(model => model.ProjectId)

        <div class="form-group">
            @Html.LabelFor(model => model.TasksName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TasksName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TasksName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.TaskStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskStartDate, "", new { @class = "text-danger" })
            </div>

            <label class="control-label col-md-3">Current Start Date:</label>
            <div class="col-md-3 form-control-static">
                @Html.DisplayFor(model => model.TaskStartDate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstimatedTaskDateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.EstimatedTaskDateEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstimatedTaskDateEnd, "", new { @class = "text-danger" })
            </div>

            <label class="control-label col-md-3">Current Start Date:</label>
            <div class="col-md-3 form-control-static">
                @Html.DisplayFor(model => model.EstimatedTaskDateEnd, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TasksStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 form-control-static">
                @Html.DropDownListFor(model => model.TasksStatus, items, "-- Select Status --")
                @Html.ValidationMessageFor(model => model.TasksStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", new { id = Model.ProjectId }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TimesheetSystem/TimesheetSystem/Views/Tasks/Index.cshtml
@model TimesheetSystem.ViewModels.ProjectTasksViewModel

@{
    ViewBag.Title = "Project Tasks";
}
<h2>Project Tasks</h2>
<h3>Project Details</h3>
<hr />

<div class="row">
    <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.ProjectName):</div>
    <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.ProjectName)</div>
    <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.ProjectDateStarted):</div>
    <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.ProjectDateStarted)</div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.ProjectStatus):</div>
    <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.ProjectStatus)</div>
    <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.EstimatedProjectDateEnd):</div>
    <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.EstimatedProjectDateEnd)</div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.ProjectType):</div>
    <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.ProjectType)</div>
    <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.EstimatedDuration):</div>
    <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.EstimatedDuration)</div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-3">@Html.LabelFor(model => model.Project.TotalDuration):</div>
    <div class="col-md-3 col-sm-3">@Html.DisplayFor(model => model.Project.TotalDuration)</div>
</div>

<hr />

<div class="row">
    <div class="col-md-10 col-sm-9 col-xs-7">
        <h3>Tasks List</h3>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-5 top-pad">
        @Html.ActionLink("Add New Task", "Create", new { id = Model.Project.ProjectId }, new { @class = "btn btn-primary btn-block"})
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tasks.SingleOrDefault().TasksName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tasks.SingleOrDefault().TasksStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tasks.SingleOrDefault().TaskType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tasks.SingleOrDefault().TaskStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tasks.SingleOrDefault().EstimatedTaskDateEnd)
        </th>
        <th>
            Options
        </th>
    </tr>

    
    @foreach (var task in Model.Tasks)
    {
        <tr>
            <td>
                @Html.ActionLink(task.TasksName, "Index", "TimeLogs", new { id = task.TasksId}, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.TasksStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.TaskType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.TaskStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.EstimatedTaskDateEnd)
            </td>
            <td>
                @Html.ActionLink("Add Log", "Create", "TimeLogs", new { id = task.TasksId }, null) |
                @Html.ActionLink("Edit", "Edit", new { id = task.TasksId }) |
                @Html.ActionLink("Delete", "Delete", new { id = task.TasksId })
            </td>
        </tr>
    }      


</table>

TimesheetSystem/TimesheetSystem/Views/Tasks/TasksPartialView.cshtml
@model IEnumerable<TimesheetSystem.DAL.Models.Tasks>

<div class="table-responsive">

    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SingleOrDefault().TasksName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SingleOrDefault().TasksStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SingleOrDefault().TaskType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SingleOrDefault().TaskStartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SingleOrDefault().EstimatedTaskDateEnd)
            </th>
            <th>
                Options
            </th>
        </tr>


        @foreach (var task in Model)
        {
            <tr id="row-@task.TasksId">
                <td>
                    @Html.ActionLink(task.TasksName, "Index", "TimeLogs", new { id = task.TasksId }, null)
                </td>
                <td id="status-@task.TasksId">
                    @Html.DisplayFor(modelItem => task.TasksStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => task.TaskType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => task.TaskStartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => task.EstimatedTaskDateEnd)
                </td>
                <td>
                    <a href="#" class="change" data-type="1" data-id="@task.TasksId">Status</a> |
                    @Html.ActionLink("Add Log", "Create", "TimeLogs", new { id = task.TasksId }, null) |
                    @Html.ActionLink("Edit", "Edit", new { id = task.TasksId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = task.TasksId })
                </td>
            </tr>
        }
    </table>

</div>